name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          set -e
          npm install || (echo 'NPM install failed' && exit 1)

      - name: Run build
        run: |
          set -e
          npm run build || (echo 'Build failed' && exit 1)

      - name: Deploy
        run: |
          set -e
          npm run deploy || (echo 'Deployment failed' && exit 1)
